# # Test-only (!) compose file for the Gohan

networks:
  bridge-net:
    external: true

services:
  api:
    ports:
      - "${GOHAN_API_EXTERNAL_PORT}:${GOHAN_API_INTERNAL_PORT}"
    extends:
      file: docker-compose.yaml
      service: api


  elasticsearch:
    ports:
      - ${GOHAN_ES_EXTERNAL_PORT_1}:${GOHAN_ES_INTERNAL_PORT_1}
    extends:
      file: docker-compose.yaml
      service: elasticsearch

  drs:
    ports:
      - "${GOHAN_DRS_EXTERNAL_PORT}:${GOHAN_DRS_INTERNAL_PORT}"
    extends:
      file: docker-compose.yaml
      service: drs
  
  drop-box:
    image: ${DROP_BOX_IMAGE}:${DROP_BOX_VERSION}
    container_name: "drop-box"
    volumes:
      - ${GOHAN_API_VCF_PATH}:/data/vcfs
      - ${GOHAN_API_GTF_PATH}:/data/gtfs
    environment:
      - BENTO_UID
      - BENTO_DEBUG=False
      - SERVICE_DATA=/data
      - BENTO_AUTHZ_ENABLED=False
      - BENTO_AUTHZ_SERVICE_URL=""
      - CORS_ORIGINS="*"
    ports:
      - "${DROP_BOX_EXTERNAL_PORT}:${DROP_BOX_INTERNAL_PORT}"
    networks:
      - ${GOHAN_DOCKER_NET}
