version: '3.7'

#TODO: volumes

# secrets:
#   metadata-app-secret:
#     file: $PWD/tmp/secrets/metadata-app-secret
#   metadata-db-user:
#     file: $PWD/tmp/secrets/metadata-db-user
#   metadata-db-secret:
#     file: $PWD/tmp/secrets/metadata-db-secret


services:
  # ingress:
  #   build:
  #     context: $PWD/lib/ingress
  #     args:
  #       BASE_IMAGE: ${BENTOV2_INGRESS_BASE_IMAGE}
  #       BASE_IMAGE_VERSION: ${BENTOV2_INGRESS_BASE_IMAGE_VERSION}
  #   image: ${BENTOV2_INGRESS_IMAGE}:${BENTOV2_INGRESS_VERSION}
  #   container_name: ${BENTOV2_INGRESS_CONTAINER_NAME}
  #   networks: 
  #     bridge-net:
  #       aliases:
  #         - bentov2.local
  #         - bentov2auth.local
  #   ports:
  #     - "80:80"
  #     - "443:443"


  # api:
  #   image: ${BENTOV2_AUTH_IMAGE}:${BENTOV2_AUTH_VERSION}
  #   container_name: ${BENTOV2_AUTH_CONTAINER_NAME}
  #   ports:
  #      - "5000:5000"
  #   # environment: 
  #   #   - KEYCLOAK_USER=${BENTOV2_AUTH_ADMIN_USER}
  #   #   - KEYCLOAK_PASSWORD=${BENTOV2_AUTH_ADMIN_PASSWORD}
  #   networks:
  #     - bridge-net
  #   # volumes:
  #   #   - ${BENTOV2_AUTH_VOL_DIR}:/opt/jboss/keycloak/standalone/data
  #   #   - ${BENTOV2_AUTH_VOL_DIR}/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml



  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - bridge-net
    environment:
      - discovery.type=single-node
    # secrets:
    #   - source: metadata-app-secret
    #     target: metadata_app_secret
    #   - source: metadata-db-user
    #     target: metadata_db_user
    #   - source: metadata-db-secret
    #     target: metadata_db_secret
    volumes: 
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    networks: 
      - bridge-net
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports: 
      - "5601:5601"

networks: 
  bridge-net:
    external: true