{
    "ApiUrl": "${BENTO_VARIANTS_PUBLIC_PROTO}://${BENTO_VARIANTS_PUBLIC_HOSTNAME}:${BENTO_VARIANTS_PUBLIC_PORT}",
    "PublicFacingElasticPath": "${BENTO_VARIANTS_ES_PUBLIC_GATEWAY_PATH}",

    "ElasticUsername": "${BENTO_VARIANTS_ES_USERNAME}",
    "ElasticPassword": "${BENTO_VARIANTS_ES_PASSWORD}"
}