name: Build and push gohan-api

on:
  release:
    types: [ published ]
  pull_request:
    branches:
      - master
      - "releases/**" # temp
      - "qa/**"  # Build PRs which will be eventually merged into patches
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather default environment variables
        id: envx
        run: |
          cp ./etc/example.env .env
          source .env
          echo "GOHAN_API_BUILDER_BASE_IMAGE=$GOHAN_API_BUILDER_BASE_IMAGE" >> $GITHUB_ENV
          echo "GOHAN_API_DEV_BASE_IMAGE=$GOHAN_API_DEV_BASE_IMAGE" >> $GITHUB_ENV
          echo "GOHAN_API_PROD_BASE_IMAGE=$GOHAN_API_PROD_BASE_IMAGE" >> $GITHUB_ENV

      - name: Load environment variables from .env file
        uses: xom9ikk/dotenv@v2
      
      - name: Run Bento build action
        uses: bento-platform/bento_build_action@v0.11.1
        with:
          context: "{{defaultContext}}:src/api"
          build-args: |
            BUILDER_BASE_IMAGE=${{ env.GOHAN_API_BUILDER_BASE_IMAGE }}
            BASE_DEV_IMAGE=${{ env.GOHAN_API_DEV_BASE_IMAGE }}
            BASE_PROD_IMAGE=${{ env.GOHAN_API_PROD_BASE_IMAGE }}
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/bento-platform/gohan-api
          development-dockerfile: dev.Dockerfile
          dockerfile: Dockerfile
