name: Build and push gohan

on:
  release:
    types: [ published ]
  pull_request:
    branches:
      - master
  push:
    branches:
      - "ci-image-builds" # temp

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up production image metadata
        id: meta
        uses: docker/metadata-action@v4
        # if: ${{ github.event_name == 'release' }}
        with:
          images: |
            ghcr.io/bento-platform/gohan
          flavor: |
            latest=true
          # tags: |
          #   type=semver,pattern=api-{{version}}
          #   type=semver,pattern=api-{{major}}.{{minor}}

      - name: Build and push production image
        uses: docker/build-push-action@v3
        # if: ${{ github.event_name == 'release' }}
        with:
          context: ./src/api/
          file: Dockerfile
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64